package com.example.bookreaderapp.model

data class VolumeInfo( var allowAnonLogging: Boolean,
                       var authors: List<String>,
                       var averageRating: Double,
                       var canonicalVolumeLink: String,
                       var categories: List<String>,
                       var contentVersion: String,
                       var description: String,
                       var imageLinks: ImageLinks,
                       var industryIdentifiers: List<IndustryIdentifier>,
                       var infoLink: String,
                       var language: String,
                       var maturityRating: String,
                       var pageCount: Int,
                       var panelizationSummary: PanelizationSummary,
                       var previewLink: String,
                       var printType: String,
                       var publishedDate: String,
                       var publisher: String,
                       var ratingsCount: Int,
                       var readingModes: ReadingModes,
                       var subtitle: String,
                       var title: String)
